// <auto-generated />
using System;
using CodeBeam.UltimateAuth.Authorization.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeBeam.UltimateAuth.Sample.BlazorServer.EFCore.Migrations.UAuthAuthorizationDb
{
    [DbContext(typeof(UAuthAuthorizationDbContext))]
    [Migration("20260326121602_InitAuthorization")]
    partial class InitAuthorization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("CodeBeam.UltimateAuth.Authorization.EntityFrameworkCore.RolePermissionProjection", b =>
                {
                    b.Property<string>("Tenant")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Permission")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Tenant", "RoleId", "Permission");

                    b.HasIndex("Tenant", "Permission");

                    b.HasIndex("Tenant", "RoleId");

                    b.ToTable("UAuth_RolePermissions", (string)null);
                });

            modelBuilder.Entity("CodeBeam.UltimateAuth.Authorization.EntityFrameworkCore.RoleProjection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Tenant", "Id")
                        .IsUnique();

                    b.HasIndex("Tenant", "NormalizedName")
                        .IsUnique();

                    b.ToTable("UAuth_Roles", (string)null);
                });

            modelBuilder.Entity("CodeBeam.UltimateAuth.Authorization.EntityFrameworkCore.UserRoleProjection", b =>
                {
                    b.Property<string>("Tenant")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Tenant", "UserKey", "RoleId");

                    b.HasIndex("Tenant", "RoleId");

                    b.HasIndex("Tenant", "UserKey");

                    b.ToTable("UAuth_UserRoles", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
