// <auto-generated />
using System;
using CodeBeam.UltimateAuth.Authentication.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeBeam.UltimateAuth.Sample.BlazorServer.EFCore.Migrations.UAuthAuthenticationDb
{
    [DbContext(typeof(UAuthAuthenticationDbContext))]
    partial class UAuthAuthenticationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("CodeBeam.UltimateAuth.Authentication.EntityFrameworkCore.AuthenticationSecurityStateProjection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CredentialType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastFailedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresReauthentication")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResetAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ResetConsumedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ResetExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ResetRequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResetTokenHash")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SecurityVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Tenant", "LockedUntil");

                    b.HasIndex("Tenant", "ResetRequestedAt");

                    b.HasIndex("Tenant", "UserKey");

                    b.HasIndex("Tenant", "UserKey", "Scope");

                    b.HasIndex("Tenant", "UserKey", "Scope", "CredentialType")
                        .IsUnique();

                    b.ToTable("UAuth_Authentication", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
