services:
  ultimateauth:
    image: ghcr.io/codebeamorg/ultimateauth:master
    container_name: ultimateauth
    restart: unless-stopped
    environment:
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - edge

networks:
  edge:
    external: true
